config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

   root 'campaigns#index'

  resources :campaigns do
    post :import_recipients
    get :send_bulk_email
  end

  resources :recipients
  resources :groups do
    post :import_recipients
  end

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_and_belongs_to_many :groups
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/delay_email.rb
class DelayEmail
  @queue = :sleep

  def self.perform(seconds)
    puts "ahoj"
    sleep(seconds)
    puts "behoj"
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :recipients
  has_and_belongs_to_many :campaign

  paginates_per 20
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  require 'valid_email'
  include ActiveModel::Validations

  belongs_to :group

  validates_uniqueness_of :email, :scope => :group_id

  validates :email, :presence => true, :email => true

  paginates_per 100
end

app/models/sent_mail.rb
class SentMail < ActiveRecord::Base
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  http_basic_authenticate_with name: "tomas", password: "tomas"

  #include ActionController::MimeResponds

  #include ActionController::MimeResponds
  #include ActionController::ImplicitRender

  include ActionController::RespondWith
end

app/controllers/campaigns_controller.rb
require 'csv'

class CampaignsController < ApplicationController

  def index
    @campaigns = Campaign.all.order(created_at: :desc)
  end

  def show
    @campaign = Campaign.find(params[:id])
    @groups = @campaign.groups.pluck(:id)

    @recipients = Recipient.where(:group_id => @groups).page params[:page]

  end

  def new
    @campaign = Campaign.new
    @groups = Group.all
  end

  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.save

    group_ids = params[:campaign][:group_ids]
    group = Group.where(:id => group_ids)
    @campaign.groups = group

    redirect_to @campaign
  end

  def edit
    @campaign = Campaign.find(params[:id])
    @groups = Group.where(:blacklist => false)
  end

  def update
    @campaign = Campaign.find(params[:id])
    @campaign.update(campaign_params)

    group_ids = params[:campaign][:group_ids]
    group = Group.where(:id => group_ids)
    @campaign.groups = group

    redirect_to @campaign
  end

  def destroy
    Campaign.find(params[:id]).destroy
    redirect_to @campaign
  end

  def send_bulk_email
    @campaign = Campaign.find(params[:campaign_id])

    @groups = @campaign.groups

    senders = []
    senders << @campaign.sender

    senders << @campaign.sender2 unless @campaign.sender2.empty?
    senders << @campaign.sender3 unless @campaign.sender3.empty?


    @blacklist_emails = Group.where(:blacklist => true).first.recipients

    @blacklist_emails =  @blacklist_emails.pluck(:email)


    @recipients = []
    @groups.each do |group|
      @recipients << group.recipients
    end

    @recipients.each do |rec_group|
      rec_group.each do |recipient|

        next if @blacklist_emails.include? recipient.email

        if SentMail.where(:campaign_id => @campaign.id, :email => recipient.email).count > 0
          puts recipient.email
          puts "already sent"
          puts "----"
          already_sent = true
        else
          already_sent = false
          puts recipient.email
          puts "not send.. sending"
          puts "----"
        end

        unless already_sent
          SentMail.create(:campaign_id => @campaign.id, :email => recipient.email)

          @body = @campaign.text.dup
          @footer = @campaign.footer.dup

          @text = @body.sub! '[::name]', recipient.name
          @text = @body.sub! '[::surname]', recipient.surname
          @text = @body if @text.nil?

          sender = senders.sample

          sleep(rand(3..10))
          Pony.mail({
                        :from => sender, :via => :smtp,
                        :headers => { 'Content-Type' => 'text/html' },
                        :via_options => { :address => 'smtp.websupport.sk', :port => 25, :domain => "websupport.sk",
                                          :user_name => sender,
                                          :password => "Randompwd2",
                                          :authentication => "plain",
                                          :domain => "websupport.sk"},
                        :to => recipient.email,
                        :subject => @campaign.subject,
                        :body => @text+@footer
                    })
        end
      end
    end

    redirect_to campaign_path(@campaign)
  end


  private

  def campaign_params
    params.require(:campaign).permit(:name, :subject, :text, :footer, :sender, :sender2, :sender3, :file, :group_ids)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  require 'csv'

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @recipients = @group.recipients.page params[:page]
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.save

    redirect_to @group
  end


  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)

    redirect_to @group
  end


  def import_recipients
    @group = Group.find(params[:group_id])

    csv_text = File.read(params[:file].path)
    csv = CSV.parse(csv_text, :headers => false)
    csv.each do |row|
      recipient = Recipient.new(:email => row[0], :name => row[1], :surname => row[2], :source => row[3])
      recipient.group_id = params[:group_id]
      recipient.save
    end

    redirect_to group_path(@group)
  end



  private

  def group_params
    params.require(:group).permit(:name, :description, :blacklist)
  end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController

  def destroy
    @recipient = Recipient.find(params[:id])
    group = @recipient.group
    @recipient.destroy

    redirect_to group
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/campaigns/edit.html.haml
= form_for @campaign do |f|
  .col-md-6
    %label
      Campaign name
    = f.text_area :name, class: "form-control", reguired: true
  .col-md-6
    %label
      Email subject
    = f.text_area :subject, class: "form-control", reguired: true
  .col-md-12
    %label
      Email body
    = f.cktext_area :text, class: "form-control", reguired: true
    %label
      Email footer
    = f.cktext_area :footer, class: "form-control"
  .col-md-4
    %label
      = f.label :sender
    = f.text_field :sender, class: "form-control", reguired: true
  .col-md-4
    %label
      = f.label :sender
    = f.text_field :sender2, class: "form-control", reguired: true
  .col-md-4
    %label
      = f.label :sender
    = f.text_field :sender3, class: "form-control", reguired: true

  .col-md-12
    %h2
      Select groups:
    - @groups.each do |group|
      = check_box_tag "campaign[group_ids][]", group.id, @campaign.groups.include?(group)
      = group.name

    %hr
  .col-md-12

    %button.btn.btn-success
      Edit

app/views/campaigns/index.html.haml
.col-md-12

  %h2
    Campaign list


  - @campaigns.each do |campaign|
    .col-md-4
      .jumbotron
        %h3
          %span.glyphicon.glyphicon-send
          = link_to campaign.name, campaign_path(campaign)
        %p
          = link_to "Update", edit_campaign_path(campaign)
          |
          = link_to "Remove", campaign, method: :delete, data: {confirm: "You sure?"}
        %br
          Groups:
          = campaign.groups.pluck(:name).join(" ")

          %br
          Created:
          = campaign.created_at

app/views/campaigns/new.html.haml
= form_for @campaign do |f|
  .col-md-6
    %label
      Campaign name
    = f.text_field :name, class: "form-control", reguired: true
  .col-md-6
    %label
      Email subject
    = f.text_field :subject, class: "form-control", reguired: true
  .col-md-12
    %label
      Email body
    = f.cktext_area :text, class: "form-control", reguired: true
    %label
      Email footer
    = f.cktext_area :footer, class: "form-control"
  .col-md-4
    %label
      = f.label :sender
    = f.text_field :sender, class: "form-control", reguired: true
  .col-md-4
    %label
      = f.label :sender
    = f.text_field :sender2, class: "form-control", reguired: true
  .col-md-4
    %label
      = f.label :sender
    = f.text_field :sender3, class: "form-control", reguired: true

  .col-md-12
    %h2
      Select groups:
    - @groups.each do |group|
      = check_box_tag "campaign[group_ids][]", group.id, @campaign.groups.include?(group)
      = group.name

    %hr
  .col-md-12

    %button.btn.btn-success
      Create

app/views/campaigns/show.html.haml
.col-md-12
  .jumbotron
    .row
      .col-md-12
        %h2
          = @campaign.name
      .col-md-6
        %h4
          Sender 1:
          = @campaign.sender
          %br
          Sender 2:
          = @campaign.sender2 unless @campaign.sender2.nil?
          %br
          Sender 3:
          = @campaign.sender3 unless @campaign.sender3.nil?
      .col-md-3.text-right
        = link_to "Send bulk mail", campaign_send_bulk_email_path(@campaign), method: :get, class: "btn btn-success"
      .col-md-3.text-left
        = link_to "Update campaign", edit_campaign_path(@campaign), class: "btn btn-info"
  .col-md-12
    .border-small
      %h3
        Subject:
      = @campaign.subject

  .col-md-6
    .border
      %h3
        Text:

      = @campaign.text.html_safe
  .col-md-6
    .border
      %h3
        Footer:

      = @campaign.footer.html_safe


  .col-md-12
    %h3
      Recipient list

    = paginate @recipients
    %table.table
      - @recipients.each do |recipient|
        %tr
          %td
            = recipient.email
          %td
            = recipient.name
          %td
            = recipient.surname
          %td
            = link_to "Remove ", recipient, method: :delete ,method: :delete
          %td
            = "Sent" if SentMail.where(:email => recipient.email, :campaign_id => @campaign.id).count > 0
            = "Not Sent" if SentMail.where(:email => recipient.email, :campaign_id => @campaign.id).count == 0

    = paginate @recipients

app/views/groups/edit.html.haml
= form_for @group do |f|
  .col-md-6
    %label
      Group name
    = f.text_area :name, class: "form-control", reguired: true
  .col-md-6
    %label
      Description
    = f.text_area :description, class: "form-control", reguired: false

  %hr
  .col-md-12

    %button.btn.btn-success
      Edit

app/views/groups/index.html.haml
.col-md-12

  %h2
    Group list


  - @groups.each do |group|
    .col-md-3
      .jumbotron
        %h3
          %span.glyphicon.glyphicon-user
          = link_to group.name, group_path(group)
        %p
          = link_to "Update", edit_group_path(group)
          |
          = link_to "Remove", group, method: :delete, data: {confirm: "You sure?"}
        %br

app/views/groups/new.html.haml
= form_for @group do |f|
  .col-md-4
    %label
      Group name
    = f.text_field :name, class: "form-control", reguired: true
  .col-md-4
    %label
      Description
    = f.text_field :description, class: "form-control", reguired: false
  .col-md-4
    %label
      Blacklist
    = f.check_box :blacklist, class: "form-control", reguired: true

  %hr
  .col-md-12

    %button.btn.btn-success
      Create group

app/views/groups/show.html.haml
.col-md-12
  .jumbotron
    .row
      .col-md-4
        %h2
          = @group.name
        %h4
          Description:
          = @group.description
      .col-md-4
        %h3
          Import emails from CSV file
        = form_tag group_import_recipients_path(@group), multipart: true do
          = file_field_tag :file
          %br
          = submit_tag "Import", class: "btn btn-success"
      .col-md-4.text-right
        = link_to "Update group metainfo", edit_group_path(@group), class: "btn btn-primary"
  .col-md-12
    %hr
    %h3
      List of recipients
    = paginate @recipients

    %table.table
      - @recipients.each do |recipient|
        .col-md-6
          %tr
            %td
              = recipient.email
            %td
              = recipient.name
            %td
              = recipient.surname
            %td
              = recipient.created_at
            %td
              = link_to "Remove ", recipient, method: :delete ,method: :delete

    = paginate @recipients

app/views/layouts/_menu.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top.padding
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
  .collapse.navbar-collapse
    %ul.nav.navbar-nav
      %li
        = link_to "Campaigns", campaigns_path
      %li
        = link_to "Create campaign", new_campaign_path(@campaign)

      %li
        = link_to "Groups", groups_path
      %li
        = link_to "Create group", new_group_path(@group)

    %ul.nav.navbar-nav.navbar-right
      Right

%hr

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Postovy holubok
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/menu"
    .container-fluid.page-row-expanded
      .col-sm-12.col-sm-offset-0.col-md-12.col-md-offset-0.main
        = yield